#背包数量 <= 9
背包数量: 3
可编辑的世界:
  - world
  - sync
不可编辑提示: 该世界不可编辑背包！
同步背包的世界:
  - sync
# 单位：秒
同步背包自动关闭时间: 30
同步背包自动选择提示: 你没有做出选择，已自动为你选择背包
# 进入同步背包世界时背包都为空执行
空背包执行命令:
  - say hello
关闭空背包执行命令: say hello
空背包提示: 您的背包都为空！
# 单位：秒
延迟同步背包的时间: 5
清除背包的世界:
  是否启用: false
  世界列表:
    - exampleWorldName
背包锁定物品:
  是否启用: false
  保存背包失败提示: 背包保存失败，需要有一把主武器和一把副武器，您的物品已返还
  lore键:
    - "主武器"
    - "副武器"
# %slot% 为点击同步的背包
背包同步成功提示: 背包 %slot% 已同步
# %number% 为保存成功的背包
背包保存成功提示: 背包 %number% 已保存！
背包栏锁定:
  是否启用: true
  超出最大物品数提示: 您携带的物品数过多！限制：
  不符合背包配置提示: 您携带的物品不符合背包配置！请检查
  # 与“不符合背包配置提示”拼接
  不符合具体提示: → 第%slot%格需要：%lore%
  # <=9
  lore键:
    0:
      - "主武器"
    1:
      - "副武器"
      - "冷兵器"